version: '4.4'

services:
  kafka1:
    image: bitnamilegacy/kafka:latest
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9090,EXTERNAL://${HOSTNAME:-localhost}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=k5-4NNJqSsC3o9UEp6ibHg
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - '8765:8080'
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka1:9090
      - KAFKA_CLUSTERS_0_NAME=kraft
    depends_on:
      - kafka1
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
      POSTGRES_USER: ${POSTGRES_USER:-test}
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  ai-service:
    build: ./ai_service
    environment:
      SERVER_PORT: 8081
      KAFKA_SERVERS: kafka1:9090
      POSTGRES_URL: jdbc:postgresql://pgvector:5432/test
      POSTGRES_USERNAME: test
      POSTGRES_PASSWORD: test
      EMBEDDING_MODEL: nomic-embed-text:latest
      CHAT_MODEL: qwen3:4b
      VECTOR_DIMENSIONS: 768
      CHAT_TEMPERATURE: 0.7
      SIMILARITY_THRESHOLD: 0.65
      TOP_K_VALUE: 6
      AI_URL: http://host.docker.internal:11434
    ports:
      - '8081:8081'
    depends_on:
      - kafka1
      - pgvector
  bot-service:
    build: ./bot_service
    environment:
      KAFKA_SERVERS: kafka1:9090
    env_file:
      - .env
    depends_on:
      - ai-service
volumes:
  ollama:
  pgvector_data: