spring:
  application:
    name: ai_service
  ai:
    openai:
      base-url: http://localhost:1234
      api-key: "lm-studio"
      chat:
        options:
          model: google/gemma-3-1b
          temperature: 0.7
          stream-usage: false