spring:
  application:
    name: ai_service
  ai:
    openai:
      base-url: ${AI_URL:http://localhost:1234}
      api-key: "lm-studio"
      chat:
        options:
          model: google/gemma-3-1b
          temperature: 0.7
          stream-usage: false
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: tg-event-handlers
      properties:
        "[spring.json.trusted.packages]": "*"
        "[spring.deserializer.value.delegate.class]": org.apache.kafka.common.serialization.StringDeserializer
    ai-service:
      topics:
        incoming-message:
          name: incoming-message
          partitions: 3
          replicas: 1
        answer-message:
          name: answer-message
          partitions: 3
          replicas: 1